# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdreal.yaml
      - stdmisc.yaml
      - otf2_aliases.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true

        # Default clock type: `default`
        $default-clock-type-name: default
        
        $include: 
          - globaldefattributes.yaml
          - globaldef.yaml

        event-record-types:
        



        #GLOBAL DEFINITIONS
          
          # OTF2 EVENTS 
          Event_Enter:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - region: uint32
                
          Event_Leave:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - region: uint32
                
        #MPI EVENTS        
          Event_MpiSend:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64

          Event_MpiIsend:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64
                - requestID: uint64

          Event_MpiIsendComplete:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - requestID: uint64

          Event_MpiIrecvRequest:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - requestID: uint64                
                
          Event_MpiRecv:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - sender: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64

          Event_MpiIrecv:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64
                - requestID: uint64

          Event_MpiRequestTest:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - requestID: uint64

          Event_MpiRequestCancelled:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64
                - requestID: uint64                

          Event_MpiCollectiveBegin:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64

          Event_MpiCollectiveEnd:
            payload-field-type:
              class: structure
              members:
                - locationID: uint64  
                - collectiveOp: uint8
                - communicator: uint32
                - root: uint32
                - sizeSent: uint64
                - sizeReceived: uint64


