# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdmisc.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true

        # Default clock type: `default`
        $default-clock-type-name: default


        event-record-types:
          GlobalDef_String:
            payload-field-type:
              class: structure
              members:
                - stringRef: uint64
                - stringValue: string
          
          GlobalDef_Region:
            payload-field-type:
              class: structure
              members:
                - regionRef: uint32
                - name: uint64
                - canonicalName: uint64
                - description: uint64
                - regionRole: uint8
                - paradigm: uint8
                - regionFlag: uint32
                - sourceFile: uint64
                - beginLineNumber: uint32
                - endLineNumber: uint32

          GlobalDef_LocationGroup:
            payload-field-type:
              class: structure
              members:
                - locationGroupRef: uint32
                - name: uint64
                - locationGroupType: uint8
                - systemTreeNodeRef: uint32
          
          GlobalDef_Location:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - name: uint64
                - locationType: uint8
                - numberOfEvents: uint64
                - locationGroupRef: uint32
                
          GlobalDef_SystemTreeNode:
            payload-field-type:
              class: structure
              members:
                - systemTreeNodeRef: uint32
                - name: uint64
                - className: uint64
                - systemTreeParent: uint32
                
          Event_Enter:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - regionRef: uint32
          Event_Leave:
          
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - regionRef: uint32

