# Needed YAML tag for the configuration object
--- !<tag:barectf.org,2020/3/config>

# Configuration's trace
trace:
  # Type of the trace
  type:
    # Add standard field type aliases
    $include:
      - stdint.yaml
      - stdmisc.yaml

    # Native byte order is little-endian
    native-byte-order: little-endian

    # One clock type
    clock-types:
      # The Linux FS platform requires a clock type named `default`
      # which has a 1-GHz frequency and the `uint64_t` C type.
      default:
        frequency: 1000000000
        $c-type: uint64_t

    # One data stream type
    data-stream-types:
      # Stream type named `default`
      default:
        # Default data stream type
        $is-default: true

        # Default clock type: `default`
        $default-clock-type-name: default


        event-record-types:
          GlobalDef_String:
            payload-field-type:
              class: structure
              members:
                - stringRef: uint32
                - stringValue: string
          
          GlobalDef_Region:
            payload-field-type:
              class: structure
              members:
                - regionRef: uint32
                - name: uint32
                - canonicalName: uint32
                - description: uint32
                - regionRole: uint8
                - paradigm: uint8
                - regionFlag: uint32
                - sourceFile: uint32
                - beginLineNumber: uint32
                - endLineNumber: uint32

          GlobalDef_LocationGroup:
            payload-field-type:
              class: structure
              members:
                - locationGroupRef: uint32
                - name: uint32
                - locationGroupType: uint8
                - systemTreeNodeRef: uint32
          
          GlobalDef_Location:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - name: uint32
                - locationType: uint8
                - numberOfEvents: uint64
                - locationGroupRef: uint32
                
          GlobalDef_SystemTreeNode:
            payload-field-type:
              class: structure
              members:
                - systemTreeNodeRef: uint32
                - name: uint32
                - className: uint32
                - systemTreeParent: uint32
          
          GlobalDef_Group:
            payload-field-type:
              class: structure
              members:
                - groupRef: uint32
                - name: uint32
                - groupType: uint8
                - paradigm: uint8
                - groupFlags: uint32
                - members:
                    field-type:
                        class: dynamic-array
                        element-field-type: uint64
                        
          GlobalDef_Comm:
            payload-field-type:
              class: structure
              members:
                - commRef: uint32
                - name: uint32
                - groupRef: uint32
                - parent: uint32
          
          # OTF2 EVENTS 
          Event_Enter:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - regionRef: uint32
                
          Event_Leave:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - regionRef: uint32
                
          Event_MpiSend:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64

          Event_MpiIsend:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64
                - requestID: uint64
                
          Event_MpiRecv:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - sender: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64

          Event_MpiIrecv:
            payload-field-type:
              class: structure
              members:
                - locationRef: uint64
                - receiver: uint32
                - communicator: uint32
                - msgTag: uint32
                - msgLength: uint64
                - requestID: uint64
